### ISSUE TITLE
Cant use trained model

### ISSUE THREAD

**Issue by yy9996** [havenhq/mamba-chat#16]
Traceback (most recent call last):
  File "/tdx/llm-download/lhylab/mamba-chat-main/chat.py", line 11, in <module>
    model = MambaLMHeadModel.from_pretrained("mamba-chat/checkpoint-50000", device="cuda", dtype=torch.float16)
  File "/home/asus/miniconda3/envs/labv2/lib/python3.10/site-packages/mamba_ssm/models/mixer_seq_simple.py", line 230, in from_pretrained
    config = load_config_hf(pretrained_model_name)
  File "/home/asus/miniconda3/envs/labv2/lib/python3.10/site-packages/mamba_ssm/utils/hf.py", line 11, in load_config_hf
    return json.load(open(resolved_archive_file))
TypeError: expected str, bytes or os.PathLike object, not NoneType

help

**Comment by yy9996** [comment]
solved in a dumb way.please fix this bug.
![L)`5 O 7K_MACT_OF4U%9IR](https://github.com/havenhq/mamba-chat/assets/102511364/f40bcb54-6d94-40db-996a-fa9a4c558555)

**Comment by Eupham** [comment]
I'm running into the same issue.  Going to see what state-spaces have that the model I'm training doesn't
Here's a notebook where this is trying to be loaded
https://colab.research.google.com/drive/1m-q--YAxhUvrRRUklgaBLJqhdEZdJo7y?usp=sharing

**Comment by Eupham** [comment]
Ok so what worked for me is I downloaded a copy of the config from hf for the size of my model and uploaded it into my hf model as config.  There's probably a trainer setting that needs to be toggled.  I'll take a look later.
