### ISSUE TITLE
Issue while installing requirements.txt

### ISSUE THREAD

**Issue by wereretot** [havenhq/mamba-chat#3]
Requirement already satisfied: packaging in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (21.3)
Collecting torch==2.1.0 (from -r requirements.txt (line 2))
  Using cached torch-2.1.0-cp311-cp311-manylinux1_x86_64.whl.metadata (25 kB)
Collecting transformers==4.35.0 (from -r requirements.txt (line 3))
  Using cached transformers-4.35.0-py3-none-any.whl.metadata (123 kB)
Collecting causal-conv1d==1.0.0 (from -r requirements.txt (line 4))
  Using cached causal_conv1d-1.0.0.tar.gz (6.4 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/rexommendation/Programs/mamba-chat/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/rexommendation/Programs/mamba-chat/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/rexommendation/Programs/mamba-chat/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wiab8kl5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wiab8kl5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-wiab8kl5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-wiab8kl5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mjmcnicholl** [comment]
I get the exact error.

**Comment by justusmattern27** [comment]
Hey, sorry for the late response - packaging should be inside requirements.txt, but for some reason, it seems to be missing here. You could try `pip install packaging` and then rerun `pip install -r requirements.txt`

**Comment by SzaremehrjardiMT** [comment]
I encountered the same issue, and installing Packaging did not resolve it. I believe the problem is related to the versions of Cuda and Torch, as well as the availability of a GPU.

**Comment by ncoder** [comment]
I got the same failure. Python 3.11.7 on a mac.  Sounds like it's not a supported configuration.

**Comment by bartanderson** [comment]
Same with 3.10 on linux
I had to download mamba. I used one environment for mamba-chat and simply dc'd to mamba.
in mamba I ran 
python setup.py build
pip install mamba_ssm
I think there was another module I had to install, probably several more if you haven't ran all of the things I did, here is my pip freeze, note your environment will likely be different for you. Just sharing my success.
aiofiles==23.2.1
altair==5.2.0
annotated-types==0.6.0
anyio==4.3.0
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.2.0
cycler==0.12.1
einops==0.7.0
exceptiongroup==1.2.0
fastapi==0.110.0
ffmpy==0.3.2
filelock==3.13.3
fonttools==4.50.0
fsspec==2024.3.1
gradio==4.23.0
gradio_client==0.14.0
h11==0.14.0
httpcore==1.0.4
httpx==0.27.0
huggingface-hub==0.22.1
idna==3.6
importlib_resources==6.4.0
Jinja2==3.1.3
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
mamba-ssm==1.2.0.post1
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.3
mdurl==0.1.2
mpmath==1.3.0
networkx==3.2.1
ninja==1.11.1.1
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.1.105
orjson==3.9.15
packaging==24.0
pandas==2.2.1
pillow==10.2.0
pydantic==2.6.4
pydantic_core==2.16.3
pydub==0.25.1
Pygments==2.17.2
pyparsing==3.1.2
python-dateutil==2.9.0.post0
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.1
referencing==0.34.0
regex==2023.12.25
requests==2.31.0
rich==13.7.1
rpds-py==0.18.0
ruff==0.3.4
safetensors==0.4.2
semantic-version==2.10.0
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
starlette==0.36.3
sympy==1.12
tokenizers==0.15.2
tomlkit==0.12.0
toolz==0.12.1
torch==2.2.1
torchaudio==2.2.1
torchvision==0.17.1
tqdm==4.66.2
transformers==4.39.1
triton==2.2.0
typer==0.10.0
typing_extensions==4.10.0
tzdata==2024.1
urllib3==2.2.1
uvicorn==0.29.0
websockets==11.0.3

**Comment by taozhiyuai** [comment]
> Hey, sorry for the late response - packaging should be inside requirements.txt, but for some reason, it seems to be missing here. You could try `pip install packaging` and then rerun `pip install -r requirements.txt`

`Collecting causal-conv1d==1.0.0 (from -r requirements.txt (line 4))
  Using cached https://mirrors.aliyun.com/pypi/packages/f8/33/f43df821036ad5dd64a4697f37459c28855e5a387dfdae10c8b1d6053b32/causal_conv1d-1.0.0.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /private/var/folders/rd/0_kt6h0545g1v749gjmryqqr0000gn/T/pip-install-8xor9lv0/causal-conv1d_3cbb803aae4d47c9ad0ac0b30efe84b5/setup.py:77: UserWarning: causal_conv1d was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rd/0_kt6h0545g1v749gjmryqqr0000gn/T/pip-install-8xor9lv0/causal-conv1d_3cbb803aae4d47c9ad0ac0b30efe84b5/setup.py", line 111, in <module>
          if bare_metal_version >= Version("11.8"):
      NameError: name 'bare_metal_version' is not defined
      
      
      torch.__version__  = 2.4.1
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`


still not work after installing packaging . MAC os
