### ISSUE TITLE
fail to install requirements.txt on MAC

### ISSUE THREAD

**Issue by taozhiyuai** [havenhq/mamba-chat#37]
`Collecting causal-conv1d==1.0.0 (from -r requirements.txt (line 4))
  Using cached https://mirrors.aliyun.com/pypi/packages/f8/33/f43df821036ad5dd64a4697f37459c28855e5a387dfdae10c8b1d6053b32/causal_conv1d-1.0.0.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      /private/var/folders/rd/0_kt6h0545g1v749gjmryqqr0000gn/T/pip-install-non_qr4h/causal-conv1d_913b0b80e0e7442ea297cf270f2028ce/setup.py:77: UserWarning: causal_conv1d was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rd/0_kt6h0545g1v749gjmryqqr0000gn/T/pip-install-non_qr4h/causal-conv1d_913b0b80e0e7442ea297cf270f2028ce/setup.py", line 111, in <module>
          if bare_metal_version >= Version("11.8"):
             ^^^^^^^^^^^^^^^^^^
      NameError: name 'bare_metal_version' is not defined
      
      
      torch.__version__  = 2.4.1
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by hg0428** [comment]
I have the same issue.

**Comment by LycoKodo** [comment]
same here
