### ISSUE TITLE
cant find torch even if it installed !

### ISSUE THREAD

**Issue by GiuseppeLeviBo** [havenhq/mamba-chat#39]
Torch 2.1 seems no more available so I have tried with Torch 2.2 and Torch 2.4 but even if they are installed the system does not find them. Could you provide a Docker? or solve this issue?
pip install -r requirements.txt
Collecting packaging (from -r requirements.txt (line 1))
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting torch==2.2 (from -r requirements.txt (line 2))
  Downloading torch-2.2.0-cp312-cp312-manylinux1_x86_64.whl.metadata (25 kB)
Collecting transformers==4.35.0 (from -r requirements.txt (line 3))
  Using cached transformers-4.35.0-py3-none-any.whl.metadata (123 kB)
Collecting causal-conv1d==1.0.0 (from -r requirements.txt (line 4))
  Using cached causal_conv1d-1.0.0.tar.gz (6.4 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/levig/mambachat/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/levig/mambachat/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/levig/mambachat/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-f01gxnv_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-f01gxnv_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-f01gxnv_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-f01gxnv_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by GiuseppeLeviBo** [comment]
Note that with the original Torch 2.1  I got this:
(base) (mambachat) levig@lnxsbarra:~/mambachat/mamba-chat$ pip install -r requirements.txt
Collecting packaging (from -r requirements.txt (line 1))
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
ERROR: Could not find a version that satisfies the requirement torch==2.1 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1)
ERROR: No matching distribution found for torch==2.1
